### ISSUE TITLE
The log is out of order

### ISSUE THREAD

**Issue by datavisorzhenbangliu** [logdna/python#19]
I've tried to use this api but the log is out of order.

I've use it like this:
```
 for i in {0..100}; do echo $i; done | python log_util.py test1
```
But the log in the logdna server is out of order.

**Comment by respectus** [comment]
@datavisorzhenbangliu 
We do not guarantee order in live tail, you must refresh the page in order to see the logs in the correct order. Your logs are stored in the correct order, and when you query them they will be displayed in the correct order. We cannot guarantee ordering of lines in the live tail query due to the nature of distributed systems. Please refresh the page and let me know if the issue persists. This is not an issue with the python library, thanks!

**Comment by datavisorzhenbangliu** [comment]
How can I query them?

**Comment by respectus** [comment]
You can find the docs for how to query your logs here: [https://docs.logdna.com/docs/search](https://docs.logdna.com/docs/search)
Generally its easy to search by host or app, otherwise you will have to search by some keyword in the log.  You can also contact support if you are having trouble finding your logs, thanks.

**Comment by datavisorzhenbangliu** [comment]
I've tried the search in the bottom box, it is still not in order.

**Comment by datavisorzhenbangliu** [comment]
curl "https://api.logdna.com/v1/export?levels=info&hosts=test1" -u INSERT_SERVICE_KEY

I've also tried the api not working either.

**Comment by respectus** [comment]
Hello @datavisorzhenbangliu,

Appreciate you reporting this bug, we've actually identified that the ordering problems you were experiencing were an issue with display on the website. We have put in a hot fix to resolve the issue with web display. If you query for your logs with the query ```host:test2``` you should see them in the correct order now.  This library was unaffected and should not have any issues with sending logs in order. Please do let me know if you experience any further issues, thanks!

**Comment by sgivony-lifesize** [comment]
Hi @respectus,
Not specifically related to the python package but seems like the right place since the issue was discussed before.
I'm trying to execute the REST API using `curl` and to export few lines but I get them in a wrong order.
Tried to get only the timestamp field from all lines and then to sort. Comparing these two results result in a non-empty diff.

**Not sorted**
```
~ > curl "https://api.logdna.com/v1/export?to=1547932227000&from=1547932219000&apps=some_app&size=20000" -u INSERT_SERVICE_KEY:xxxxx | jq -r ._ts > a
```
**Sorted**
```
~ > curl "https://api.logdna.com/v1/export?to=1547932227000&from=1547932219000&apps=some_app&size=20000" -u INSERT_SERVICE_KEY:xxxxx | jq -r ._ts | sort > b
```
**Comparison**
```
~ > diff a b > /dev/null
~ > echo $?
1
```

Is that the expected behavior? Thanks
